add: sdk branch
browserstack/java-playwright-browserstack pull request #2
Opened 2023-06-02 05:42 UTC by Ankit098

2023-06-04 17:18 UTC, karanshah-browserstack requested changes

2023-06-04 17:18 UTC, karanshah-browserstack commented on src/test/java/runners/BstackRunner.java
> -                platform.put("browserstack.username", username);
Fetch username & accesskey from env var or yml file so if user doesn't have IDE plugin install and runs via IDE it at least trigger a runs on BS.

2023-06-04 17:18 UTC, karanshah-browserstack commented on src/test/resources/conf/browserstack.conf.json
>        "os": "Windows",
Get Rid of this file as all caps will be governed through yml file

2023-06-05 16:57 UTC, karanshah-browserstack approved these changes

2023-06-05 16:57 UTC, karanshah-browserstack commented on pom.xml
> +            <id>local</id>
sample-local-test

2023-06-05 16:57 UTC, karanshah-browserstack commented on pom.xml
> +            <id>sample</id>
sample-test

2023-06-05 16:57 UTC, karanshah-browserstack requested changes

2023-06-05 16:57 UTC, karanshah-browserstack commented on pom.xml
>          <tests.single>**/tests.SampleTest.java</tests.single>
Rename to tests.sample

2023-06-05 17:01 UTC, Ankit098 commented on pom.xml
>          <tests.single>**/tests.SampleTest.java</tests.single>
done

2023-06-05 17:03 UTC, karanshah-browserstack requested changes

2023-06-05 17:03 UTC, karanshah-browserstack commented on pom.xml
> +                        <include>${tests.single}</include>
```suggestion
                        <include>${tests.sample}</include>
```

2023-06-05 17:03 UTC, karanshah-browserstack approved these changes

2023-06-05 17:30 UTC, merged